<?php

namespace Tests\Feature;

use App\Enums\Status;
use App\Models\Client;
use App\Models\Project;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Str;
use Tests\TestCase;

class ProjectTest extends TestCase
{
    use RefreshDatabase;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        User::factory(10)->create();
        Client::factory(10)->create();
        Project::factory(10)->create();
    }

    public function testIndexMethodReturnsProjectCollection()
    {
        $response = $this->getJson(route('projects.index'));

        $response->assertOk();
        $response->assertJsonStructure([
            [
                'title',
                'description',
                'user_id',
                'client_id',
                'deadline',
                'status',
            ],
        ]);
    }

    public function testStoreMethodCreatesNewRecord()
    {
        $statuses = [Status::OPEN, Status::IN_PROGRESS, Status::CLOSED];
        $userData = [
            'title' => Str::random(),
            'description' => Str::random(25),
            'user_id' => rand(1, 10),
            'client_id' => rand(1, 10),
            'deadline' => fake()->date(),
            'status' => ($statuses[array_rand($statuses)])->name,
        ];

        $response = $this->postJson(route('projects.store'), $userData);

        $response->assertCreated();
        $response->assertExactJson(['message' => 'Project successfully created!']);
        $this->assertDatabaseHas('projects', $userData);
    }

    public function testStoreMethodFailsWithInCorrectData()
    {
        $userData = [
            'title' => fake()->word().Str::random(25),
            'description' => '',
            'user_id' => rand(1, 1000),
            'client_id' => 0,
            'deadline' => fake()->date(),
            'status' => '',
        ];

        $response = $this->postJson(route('projects.store'), $userData);

        $response->assertUnprocessable();
        $response->assertJsonValidationErrors(['title', 'description', 'status']);
        $this->assertDatabaseMissing('projects', $userData);
    }

    public function testStoreMethodFailsWithInCorrectUserIdAndClientId()
    {
        $statuses = [Status::OPEN, Status::IN_PROGRESS, Status::CLOSED];
        $userData = [
            'title' => Str::random(),
            'description' => Str::random(25),
            'user_id' => rand(1, 1000),
            'client_id' => 0,
            'deadline' => fake()->date(),
            'status' => $statuses[array_rand($statuses)],
        ];

        $response = $this->postJson(route('projects.store'), $userData);

        $response->assertJson(['message' => 'Something went wrong...']);
        $this->assertDatabaseMissing('projects', $userData);
    }

    public function testShowMethodReturnProjectResource()
    {
        $response = $this->getJson(route('projects.show', 1));

        $response->assertOk();
        $response->assertJsonStructure([
            'title',
            'description',
            'user_id',
            'client_id',
            'deadline',
            'status',
        ]);
    }

    public function testUpdateMethodUpdatesExistingRecord()
    {
        $statuses = [Status::OPEN, Status::IN_PROGRESS, Status::CLOSED];
        $userData = [
            'title' => Str::random(),
            'description' => Str::random(25),
            'user_id' => rand(1, 10),
            'client_id' => rand(1, 10),
            'deadline' => fake()->date(),
            'status' => ($statuses[array_rand($statuses)])->name,
        ];

        $response = $this->putJson(route('projects.update', 1), $userData);

        $response->assertOk();
        $response->assertExactJson(['message' => 'Project successfully updated!']);
        $this->assertDatabaseHas('projects', $userData);
    }

    public function testUpdatesMethodFailsWithInCorrectData()
    {
        $userData = [
            'title' => fake()->word().Str::random(25),
            'description' => '',
            'user_id' => rand(1, 1000),
            'client_id' => 0,
            'deadline' => fake()->date(),
            'status' => '',
        ];

        $response = $this->putJson(route('projects.update', 1), $userData);

        $response->assertUnprocessable();
        $this->assertDatabaseMissing('projects', $userData);
    }

    public function testDestroyMethodDeletesExistingRecord()
    {
        $response = $this->deleteJson(route('projects.destroy', 1));

        $response->assertNoContent();
        $this->assertDatabaseCount('projects', 9);
    }

    public function testDestroyMethodFailsBecauseOfRecordNotFound()
    {
        $response = $this->deleteJson(route('projects.destroy', 100));

        $response->assertNotFound();
        $this->assertDatabaseCount('projects', 10);
    }
}
